#!/bin/bash

. ${HOME}/.bash_profile

if [[ -z $DFIFHOME ]] ; then
	BASE=$HOME
else
	BASE=$DFIFHOME
fi

SHLDIR=${BASE}/bin/shell
source ${SHLDIR}/.dbcinfo

PNM=$(basename $0)
LOGDIR=${BASE}/../log/etc
LOGFILE=${LOGDIR}/${PNM%.*}.log

sqlplus ${USER}/${PSWD}@${DBNM} << _EOF_

SPOOL ${LOGFILE}

SELECT BOOK_HSX + BOOK_HNX as TOT, HSX_SENT+HNX_SENT TOTSND, HSX_NOTSND+HNX_NOTSND TOTQ
       , BOOK_HSX HSX, HSX_SENT HSXSND, HSX_NOTSND HSX_Q
			 , BOOK_HNX HNX, HNX_SENT HNXSND, HNX_NOTSND HNX_Q
	FROM (
		SELECT 
			(SELECT COUNT( *) FROM TSO01M00 WHERE MKT_TRD_TP = '01' ) AS BOOK_HSX, 
			(SELECT COUNT( *) FROM TSO01M00 WHERE MKT_TRD_TP <> '01' ) AS BOOK_HNX, 
			(SELECT COUNT( *) FROM XIH03M11) AS HSX_ALL,
			(SELECT COUNT( *) FROM XIH03M11 WHERE SND_TP = '3') AS HSX_SENT,
			(SELECT COUNT( *) FROM XIH03M11 WHERE SND_TP = '0') AS HSX_NOTSND,
			(SELECT COUNT( *) FROM XIH03M11 WHERE SND_TP = '9') AS HSX_ERR,
			(SELECT COUNT( *) FROM XIH03M12) AS HNX_ALL,
			(SELECT COUNT( *) FROM XIH03M12 WHERE SND_TP = '3') AS HNX_SENT,
			(SELECT COUNT( *) FROM XIH03M12 WHERE SND_TP = '0') AS HNX_NOTSND,
			(SELECT COUNT( *) FROM XIH03M12 WHERE SND_TP = '9') AS HNX_ERR
			FROM DUAL
		)
;

SPOOL OFF

_EOF_

echo "================ END[`date +%H:%M:%S`] ==================" >> ${LOGFILE}

exit
