#!/bin/bash

. ${HOME}/.bash_profile

if [[ -z $DFIFHOME ]] ; then
	BASE=$HOME
else
	BASE=$DFIFHOME
fi

SHLDIR=${BASE}/bin/shell
source ${SHLDIR}/.dbcinfo

LOGDIR=${BASE}/../log/etc
PNM=$(basename $0)
LOGFILE=${LOGDIR}/${PNM%.*}.log

sqlplus ${USER}/${PSWD}@${DBNM} << _EOF_
--spool ${LOGFILE}

SELECT 
	TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') TODAY,
	VN.VWDATE WORKDAY
FROM DUAL;

INSERT INTO VN.XIB01H00
SELECT * FROM VN.XIB01M00
WHERE TRD_DT < VN.FXC_VORDERDT_G(SYSDATE, -1);

DELETE FROM VN.XIB01M00
WHERE TRD_DT < VN.FXC_VORDERDT_G(SYSDATE, -1);

COMMIT WORK;

INSERT INTO VN.VTB01H00
SELECT * FROM VN.VTB01M00
WHERE TRD_DT < VN.FXC_VORDERDT_G(SYSDATE, -1);

DELETE FROM VN.VTB01M00
WHERE TRD_DT < VN.FXC_VORDERDT_G(SYSDATE, -1);

COMMIT WORK;

INSERT INTO VN.VTB01H10
SELECT * FROM VN.VTB01M10
WHERE TRD_DT < VN.FXC_VORDERDT_G(SYSDATE, -1);

DELETE FROM VN.VTB01M10
WHERE TRD_DT < VN.FXC_VORDERDT_G(SYSDATE, -1);

COMMIT WORK;

--spool off

_EOF_

echo "================ END[`date +%H:%M:%S`] ==================" >> ${LOGFILE}

exit


