#!/bin/bash

. ${HOME}/.bash_profile

if [[ -z $DFIFHOME ]] ; then
	BASE=$HOME
else
	BASE=$DFIFHOME
fi

SHLDIR=${BASE}/bin/shell
source ${SHLDIR}/holiopt
source ${SHLDIR}/.dbcinfo

#ACCLIST=('%')
ALL_ACCLIST="('000001','666666')"
NET_ACCLIST="('000001','666666')"
NONNET_ACCLIST="('000001','666666')"

LOGDIR=${BASE}/../log/etc
PNM=$(basename $0)
LOGFILE=${LOGDIR}/${PNM%.*}.log

sqlplus ${USER}/${PSWD}@${DBNM} << _EOF_
spool ${LOGFILE}

DELETE FROM DIR.FTS_ORDER 
WHERE BSNS_DATE IN ( SELECT BSNS_DATE FROM DIR.FTS_SYSTEM_INFO )
--AND ACNTNO LIKE ${ALL_ACCLIST}
;

DELETE FROM DIR.FTS_DEAL 
WHERE BSNS_DATE IN ( SELECT BSNS_DATE FROM DIR.FTS_SYSTEM_INFO )
--AND ACNTNO LIKE ${ALL_ACCLIST}
;

DELETE FROM DIR.FTS_POSITION
WHERE BSNS_DATE IN ( SELECT BSNS_DATE FROM DIR.FTS_SYSTEM_INFO )
--AND ACNTNO LIKE ${ALL_ACCLIST}
;

DELETE FROM DIR.FTS_POSITION_SUM
WHERE BSNS_DATE IN ( SELECT BSNS_DATE FROM DIR.FTS_SYSTEM_INFO )
--AND ACNTNO LIKE ${ALL_ACCLIST}
;

DELETE FROM DIR.FTS_POS_CLEAR
WHERE BSNS_DATE IN ( SELECT BSNS_DATE FROM DIR.FTS_SYSTEM_INFO )
--AND ACNTNO LIKE ${ALL_ACCLIST}
;

DELETE FROM DIR.FTS_POS_TRAD
WHERE BSNS_DATE IN ( SELECT BSNS_DATE FROM DIR.FTS_SYSTEM_INFO )
--AND ACNTNO LIKE ${ALL_ACCLIST}
;

DELETE FROM DIR.FTS_POS_TRANSFER
WHERE BSNS_DATE IN ( SELECT BSNS_DATE FROM DIR.FTS_SYSTEM_INFO )
--AND ACNTNO LIKE ${ALL_ACCLIST}
;

DELETE FROM DIR.FTS_PRE_ASSET_INOUT
WHERE BSNS_DATE IN ( SELECT BSNS_DATE FROM DIR.FTS_SYSTEM_INFO )
--AND ACNTNO LIKE ${ALL_ACCLIST}
;

UPDATE DIR.FTS_DEPOSIT SET
	TDEPO_AMT = 0
	,SUBST_AMT =0
	,PRE_CASH_OUTAMT=0
	,PRE_SUBST_OUTAMT =0
WHERE BSNS_DATE IN ( SELECT BSNS_DATE FROM DIR.FTS_SYSTEM_INFO )
--AND ACNTNO LIKE ${ALL_ACCLIST}
;

-- Netting Type
UPDATE FTS_ACNT_MAST SET
	ACNT_HEG_SECT = '0'
WHERE ACNTNO IN ${NET_ACCLIST}
;

-- Non-Netting Type
UPDATE FTS_ACNT_MAST SET
	ACNT_HEG_SECT = '1'
WHERE ACNTNO IN ${NONNET_ACCLIST}
;

COMMIT WORK;

spool off

_EOF_

echo "================ END[`date +%H:%M:%S`] ==================" >> ${LOGFILE}

exit

