#!/bin/bash

. ${HOME}/.bash_profile

if [[ -z $DFIFHOME ]] ; then
	BASE=$HOME
else
	BASE=$DFIFHOME
fi

SHLDIR=${BASE}/bin/shell
source ${SHLDIR}/.dbcinfo

LOGDIR=${BASE}/../log/vts
LOGFILE=${LOGDIR}/vex_hsx_init.log

sqlplus ${USER}/${PSWD}@${DBNM} << _EOF_
spool ${LOGFILE}

SELECT 
	TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') TODAY,
	VN.VWDATE WORKDAY
FROM DUAL;

DROP SEQUENCE VN.VT_CONFIRM_NO;
CREATE SEQUENCE VN.VT_CONFIRM_NO
MINVALUE 1
MAXVALUE 884735
INCREMENT BY 1
CYCLE
NOORDER
CACHE 20;
GRANT SELECT ON VN.VT_CONFIRM_NO TO PUBLIC;

DROP SEQUENCE VN.VT_TRD_BUY_BOOK_SEQ;
CREATE SEQUENCE VN.VT_TRD_BUY_BOOK_SEQ
MINVALUE 1
MAXVALUE 99999999
INCREMENT BY 1
NOCYCLE
NOORDER
CACHE 20;
GRANT SELECT ON VN.VT_TRD_BUY_BOOK_SEQ TO PUBLIC;

DROP SEQUENCE VN.VT_TRD_SELL_BOOK_SEQ;
CREATE SEQUENCE VN.VT_TRD_SELL_BOOK_SEQ
MINVALUE 1
MAXVALUE 99999999
INCREMENT BY 1
NOCYCLE
NOORDER
CACHE 20;
GRANT SELECT ON VN.VT_TRD_SELL_BOOK_SEQ TO PUBLIC;

DROP SEQUENCE VN.VEX03M00_SEQ;
CREATE SEQUENCE VN.VEX03M00_SEQ
MINVALUE 1
MAXVALUE 99999999
START WITH 1
INCREMENT BY 1
NOCYCLE
NOORDER
CACHE 20;
GRANT SELECT ON VN.VEX03M00_SEQ TO PUBLIC;

DROP SEQUENCE VN.VEX_ACCP_NO_SEQ;
CREATE SEQUENCE VN.VEX_ACCP_NO_SEQ
MINVALUE 1
MAXVALUE 99999999
START WITH 1
INCREMENT BY 1
NOCYCLE
NOORDER
CACHE 20;
GRANT SELECT ON VN.VEX_ACCP_NO_SEQ TO PUBLIC;

UPDATE  VN.VT_STK_DAY
SET
		TOT_TRD_QTY   = 0 ,
		TOT_TRD_AMT   = 0 ,
		HIGH_PRI      = 0 ,
		LOW_PRI       = 0 ,
		MAX_PRI       = DECODE(TM_MAX_PRI,0,MAX_PRI,TM_MAX_PRI),
		DN_PRI        = DECODE(TM_DN_PRI,0,DN_PRI,TM_DN_PRI),
		TM_MAX_PRI    = 0 ,
		TM_DN_PRI     = 0 ,
		STRT_PRI      = 0 ,
		LST_PRE_PRI   = 0 ,
		BUY_PRI_STP1  = 0 ,
		BUY_QTY_STP1  = 0 ,
		BUY_PRI_STP2  = 0 ,
		BUY_QTY_STP2  = 0 ,
		BUY_PRI_STP3  = 0 ,
		BUY_QTY_STP3  = 0 ,
		SELL_PRI_STP1 = 0 ,
		SELL_QTY_STP1 = 0 ,
		SELL_PRI_STP2 = 0 ,
		SELL_QTY_STP2 = 0 ,
		SELL_PRI_STP3 = 0 ,
		SELL_QTY_STP3 = 0 ;
COMMIT WORK;

DELETE FROM VN.VEX02M00;
COMMIT WORK;

DELETE FROM VN.VEX03M00;
COMMIT WORK;

DELETE FROM VN.VEX03M11;
COMMIT WORK;

DELETE FROM VN.VT_ORD_MST;
COMMIT WORK;

DELETE FROM VN.VT_TRD_BUY_BOOK;
COMMIT WORK;

DELETE FROM VN.VT_TRD_SELL_BOOK;
COMMIT WORK;

spool off

_EOF_

echo "================ END[`date +%H:%M:%S`] ==================" >> ${LOGFILE}

exit


